version: "3"
services:

  # core
  db:
    image: "point-db"
    restart: always
    environment:
      POSTGRES_USER: point
      POSTGRES_PASSWORD: point
      POSTGRES_DB: point
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

  redis-storage:
    image: "redis:alpine"
    sysctls:
      net.core.somaxconn: '511'
    volumes:
      - ./data/redis/storage:/data

  redis-cache:
    image: "redis:alpine"
    sysctls:
      net.core.somaxconn: '511'
    volumes:
      - ./data/redis/cache:/data

  redis-queue:
    image: "redis:alpine"
    sysctls:
      net.core.somaxconn: '511'
    volumes:
      - ./data/redis/queue:/data

  redis-pubsub:
    image: "redis:alpine"
    sysctls:
      net.core.somaxconn: '511'
    volumes:
      - ./data/redis/pubsub:/data

  # imgproc
  imgproc:
    build:
      context: ./imgproc
    volumes:
      - ./core:/home/point/core
      - ./imgproc:/home/point/imgproc
      - ./img:/home/point/img
      - ./log:/home/point/log
    depends_on:
      - redis-cache
      - redis-imgproc

  redis-imgproc:
    image: "redis:alpine"
    sysctls:
      net.core.somaxconn: '511'
    volumes:
      - ./data/redis/imgproc:/data

  # web
  www:
    build:
      context: ./www
      dockerfile: Dockerfile.www
    volumes:
      - ./core:/home/point/core
      - ./www:/home/point/www
      - ./img:/home/point/img
      - ./doc:/home/point/doc
      - ./log:/home/point/log
    depends_on:
      - db
      - redis-cache
      - redis-storage
      - redis-queue
      - redis-pubsub
      - redis-sessions
      - redis-imgproc

  websocket:
    build:
      context: ./www
      dockerfile: Dockerfile.websocket
    volumes:
      - ./core:/home/point/core
      - ./www:/home/point/www
      - ./log:/home/point/log
    depends_on:
      - db
      - redis-cache
      - redis-storage
      - redis-queue
      - redis-pubsub
      - redis-sessions

  redis-sessions:
    image: "redis:alpine"
    sysctls:
      net.core.somaxconn: '511'
    volumes:
      - ./data/redis/sessions:/data

  nginx:
    image: "nginx"
    volumes:
      - ./ssl:/home/point/ssl
      - ./www/etc/nginx/www.conf:/etc/nginx/conf.d/1-www.conf
      - ./imgproc/etc/nginx/imgproc.conf:/etc/nginx/conf.d/2-imgproc.conf
      - ./www/etc/nginx/www.vars:/etc/nginx/conf.d/www.vars
      - ./img:/home/point/img
      - ./doc:/home/point/doc
      - ./www/static:/home/point/www/static
    depends_on:
      - www
      - websocket
    ports:
      - "80:80"
      - "443:443"

  # xmpp
  prosody:
    build:
      context: ./xmpp
      dockerfile: Dockerfile.prosody
    volumes:
      - ./xmpp/etc/prosody/prosody.cfg.lua:/etc/prosody/prosody.cfg.lua
      - ./ssl:/home/point/ssl
      - ./data/prosody:/var/lib/prosody
    environment:
      - XMPP_BOT_USERNAME=p
      - XMPP_BOT_DOMAIN=point.local
      - XMPP_BOT_PASSWORD=123
    ports:
      - "5222:5222"
      - "5269:5269"

  bot:
    build:
      context: ./xmpp
      dockerfile: Dockerfile.bot
    volumes:
      - ./core:/home/point/core
      - ./xmpp:/home/point/xmpp
    depends_on:
      - db
      - redis-cache
      - redis-storage
      - redis-queue
      - redis-pubsub
      - prosody

